using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AC_Texture_Editor
{
    public static class ObjectDatabase
    {
        public static string[] Faces = new string[64]
        {
            "Male #1 Eyes with Eyelashes",
            "Male #2 Circle Eyes with Eyebrows",
            "Male #3 Eyes with Purple Bags",
            "Male #4 Circle Dot Eyes",
            "Male #5 Large Oval Eyes",
            "Male #6 Half Oval Eyes",
            "Male #7 Eyes with Flushed Cheeks",
            "Male #8 Blue Circle Eyes",
            "Female #1 Full Black Eyes (Pink Hair)",
            "Female #2 Black Squinty Eyes (Purple Hair)",
            "Female #3 Eyes with Flushed Cheeks (Brown Hair)",
            "Female #4 Eyes with Bags (Blue Hair)",
            "Female #5 Oval Eyes with Eyelashes (Pink Hair)",
            "Female #6 Half Oval Eyes (Ginger Hair)",
            "Female #7 Blue Eyes (Dark Blue Hair)",
            "Female #8 Circle Eyes with Eyelashes (Red Hair)",
            "Male #1 Bee Sting",
            "Male #2 Bee Sting",
            "Male #3 Bee Sting",
            "Male #4 Bee Sting",
            "Male #5 Bee Sting",
            "Male #6 Bee Sting",
            "Male #7 Bee Sting",
            "Male #8 Bee Sting",
            "Female #1 Bee Sting",
            "Female #2 Bee Sting",
            "Female #3 Bee Sting",
            "Female #4 Bee Sting",
            "Female #5 Bee Sting",
            "Female #6 Bee Sting",
            "Female #7 Bee Sting",
            "Female #8 Bee Sting",
            "Lloyd Face [Male #1]",
            "Lloyd Face [Male #2]",
            "Lloyd Face [Male #3]",
            "Lloyd Face [Male #4]",
            "Lloyd Face [Male #5]",
            "Lloyd Face [Male #6]",
            "Lloyd Face [Male #7]",
            "Lloyd Face [Male #8]",
            "Lloyd Face [Female #1]",
            "Lloyd Face [Female #2]",
            "Lloyd Face [Female #3]",
            "Lloyd Face [Female #4]",
            "Lloyd Face [Female #5]",
            "Lloyd Face [Female #6]",
            "Lloyd Face [Female #7]",
            "Lloyd Face [Female #8]",
            "Lloyd Face (Bee Sting) [Male #1]",
            "Lloyd Face (Bee Sting) [Male #2]",
            "Lloyd Face (Bee Sting) [Male #3]",
            "Lloyd Face (Bee Sting) [Male #4]",
            "Lloyd Face (Bee Sting) [Male #5]",
            "Lloyd Face (Bee Sting) [Male #6]",
            "Lloyd Face (Bee Sting) [Male #7]",
            "Lloyd Face (Bee Sting) [Male #8]",
            "Lloyd Face (Bee Sting) [Female #1]",
            "Lloyd Face (Bee Sting) [Female #2]",
            "Lloyd Face (Bee Sting) [Female #3]",
            "Lloyd Face (Bee Sting) [Female #4]",
            "Lloyd Face (Bee Sting) [Female #5]",
            "Lloyd Face (Bee Sting) [Female #6]",
            "Lloyd Face (Bee Sting) [Female #7]",
            "Lloyd Face (Bee Sting) [Female #8]"
        };

        public static string[] Shirts = new string[256]
        {
            "Flame Shirt",
            "Paw Shirt",
            "Wavy Pink Shirt",
            "Furture Shirt",
            "Bold Check Shirt",
            "Mint Gingham",
            "Bad Plaid Shirt",
            "Speedway Shirt",
            "Folk Shirt",
            "Daisy Shirt",
            "Wavy Tan Shirt",
            "Optical Shirt",
            "Rugby Shirt",
            "Sherbet Gingham",
            "Yellow Tartan",
            "Gelato Shirt",
            "Work Uniform",
            "Patched Shirt",
            "Plum Kimono",
            "Somber Robe",
            "Red Sweatsuit",
            "Blue Sweatsuit",
            "Red Puffy Vest",
            "Blue Puffy Vest",
            "Summer Robe",
            "Bamboo Robe",
            "Red Aloha Shirt",
            "Blue Aloha Shirt",
            "Dark Polka Shirt",
            "Lite Polka Shirt",
            "Lovely Shirt",
            "Citrus Shirt",
            "Kiwi Shirt",
            "Watermelon Shirt",
            "Strawberry Shirt",
            "Grape Shirt",
            "Melon Shirt",
            "Jingle Shirt",
            "Blossom Shirt",
            "Icy Shirt",
            "Crewel Shirt",
            "Tropical Shirt",
            "Ribbon Shirt",
            "Fall Plaid Shirt",
            "Fiendish Shirt",
            "Chevron Shirt",
            "Ladybug Shirt",
            "Botanical Shirt",
            "Anju's Shirt",
            "Kaffe's Shirt",
            "Lavender Robe",
            "Blue Grid Shirt",
            "Butterfly Shirt",
            "Blue Tartan",
            "Gracie's Top",
            "Orange Tie-Die",
            "Purple Tie-Die",
            "Green Tie-Die",
            "Blue Tie-Die",
            "Red Tie-Die",
            "One-Ball Shirt",
            "Two-Ball Shirt",
            "Three-Ball Shirt",
            "Four-Ball Shirt",
            "Five-Ball Shirt",
            "Six-Ball Shirt",
            "Seven-Ball Shirt",
            "Eight-Ball Shirt",
            "Nine-Ball Shirt",
            "Arctic Camo",
            "Jungle Camo",
            "Desert Camo",
            "Rally Shirt",
            "Racer Shirt",
            "Racer 6 Shirt",
            "Fish Bone Shirt",
            "Spiderweb Shirt",
            "Zipper Shirt",
            "Bubble Shirt",
            "Yellow Bolero",
            "Nebula Shirt",
            "Neo-Classic Knit",
            "Noble Shirt",
            "Turnip Top",
            "Oft-Seen Print",
            "Ski Sweater",
            "Circus Shirt",
            "Patchwork Top",
            "Mod Top",
            "Hippie Shirt",
            "Rickrack Shirt",
            "Diner Uniform",
            "Shirt Circuit",
            "U R Here Shirt",
            "Yodel Shirt",
            "Pulse Shirt",
            "Prism Shirt",
            "Star Shirt",
            "Straw Shirt",
            "Noodle Shirt",
            "Dice Shirt",
            "Kiddie Shirt",
            "Frog Shirt",
            "Moody Blue Shirt",
            "Cloudy Shirt",
            "Fortune Shirt",
            "Skull Shirt",
            "Desert Shirt",
            "Aurora Knit",
            "Winter Sweater",
            "Go-Go Shirt",
            "Jade Check Print",
            "Blue Check Print",
            "Red Grid Shirt",
            "Flicker Shirt",
            "Floral Knit",
            "Rose Shirt",
            "Sunset Top",
            "Chain-Gang Shirt",
            "Spring Shirt",
            "Bear Shirt",
            "MVP Shirt",
            "Silk Bloom Shirt",
            "Pop Bloom Shirt",
            "Loud Bloom Shirt",
            "Hot Spring Shirt",
            "New Spring Shirt",
            "Deep Blue Tee",
            "Snowcone Shirt",
            "Ugly Shirt",
            "Sharp Outfit",
            "Painter's Smock",
            "Spade Shirt",
            "Blossoming Shirt",
            "Peachy Shirt",
            "Static Shirt",
            "Rainbow Shirt",
            "Groovy Shirt",
            "Loud Line Shirt",
            "Dazed Shirt",
            "Red Bar Shirt",
            "Blue Stripe Knit",
            "Earthy Knit",
            "Spunky Knit",
            "Deer Shirt",
            "Blue Check Shirt",
            "Light Line Shirt",
            "Blue Pinestripe",
            "Diamond Shirt",
            "Lime Line Shirt",
            "Big Bro's Shirt",
            "Green Bar Shirt",
            "Yellow Bar Shirt",
            "Monkey Shirt",
            "Polar Fleece",
            "Ancient Knit",
            "Fish Knit",
            "Vertigo Shirt",
            "Misty Shirt",
            "Stormy Shirt",
            "Red Scale Shirt",
            "Blue Scale Shirt",
            "Heart Shirt",
            "Yellow Pinstripe",
            "Club Shirt",
            "Li'l Bro's Shirt",
            "Argyle Knit",
            "Caveman Tunic",
            "Café Shirt",
            "Tiki Shirt",
            "A Shirt",
            "Checkered Shirt",
            "No. 1 Shirt",
            "No. 2 Shirt",
            "No. 3 Shirt",
            "No. 4 Shirt",
            "No. 5 Shirt",
            "No. 23 Shirt",
            "No. 67 Shirt",
            "BB Shirt",
            "Beatnik Shirt",
            "Moldy Shirt",
            "Houndstooth Tee",
            "Big Star Shirt",
            "Orange Pinstripe",
            "Twinkle Shirt",
            "Funky Dot Shirt",
            "Crossing Shirt",
            "Splendid Shirt",
            "Jagged Shirt",
            "Denim Shirt",
            "Cherry Shirt",
            "Gumdrop Shirt",
            "Barber Shirt",
            "Concierge Shirt",
            "Fresh Shirt",
            "Far-Out Shirt",
            "Dawn Shirt",
            "Striking Outfit",
            "Red Check Shirt",
            "Berry Gingham",
            "Lemon Gingham",
            "Dragon Suit",
            "G Logo Shirt",
            "Tin Shirt",
            "Jester Shirt",
            "Pink Tartan",
            "Waffle Shirt",
            "Gray Tartan",
            "Windsock Shirt",
            "Trendy Top",
            "Green Ring Shirt",
            "White Ring Shirt",
            "Snappy Print",
            "Chichi Print",
            "Wave Print",
            "Checkerboard Tee",
            "Subdued Print",
            "Airy Shirt",
            "Coral Shirt",
            "Leather Jerkin",
            "Zebra Print",
            "Tiger Print",
            "Cow Print",
            "Leopard Print",
            "Danger Shirt",
            "Big Dot Shirt",
            "Puzzling Shirt",
            "Exotic Shirt",
            "Houndstooth Knit",
            "Uncommon Shirt",
            "Dapper Shirt",
            "Gaudy Sweater",
            "Cozy Sweater",
            "Comfy Sweater",
            "Classic Top",
            "Vogue Top",
            "Laced Shirt",
            "Natty Shirt",
            "Citrus Gingham",
            "Cool Shirt",
            "Dreamy Shirt",
            "Flowery Shirt",
            "Caterpillar Tee",
            "Shortcake Shirt",
            "Whirly Shirt",
            "Thunder Shirt",
            "Giraffe Print",
            "Swell Shirt",
            "Toad Print",
            "Grass Shirt",
            "Mosaic Shirt",
            "Fetching Outfit",
            "Snow Shirt",
            "Melon Gingham",
            "Mannequin Wood Shirt"
        };

        public static string[] Carpets = new string[71]
        {
            "Plush Carpet",
            "Classic Carpet",
            "Checkered Tile",
            "Old Flooring",
            "Red Tile",
            "Birch Flooring",
            "Classroom Floor",
            "Lovely Carpet",
            "Exotic Rug",
            "Mossy Carpet",
            "18 Mat Tatami",
            "8 Mat Tatami",
            "Citrus Carpet",
            "Cabin Rug",
            "Closed Road",
            "Lunar Surface",
            "Sand Garden",
            "Spooky Carpet",
            "Western Desert",
            "Green Rug",
            "Blue Flooring",
            "Regal Carpet",
            "Ranch Flooring",
            "Modern Tile",
            "Cabana Flooring",
            "Snowman Carpet",
            "Backyard Lawn",
            "Music Room Floor",
            "Plaza Tile",
            "Kitchen Tile",
            "Ornate Rug",
            "Tatami Floor",
            "Bamboo Flooring",
            "Kitchen Flooring",
            "Charcoal Tile",
            "Stone Tile",
            "Imperial Tile",
            "Opulent Rug",
            "Slate Flooring",
            "Ceramic Tile",
            "Fancy Carpet",
            "Cowhide Rug",
            "Steel Flooring",
            "Office Flooring",
            "Ancient Tile",
            "Exquisite Rug",
            "Sandlot",
            "Jingle Carpet",
            "Daisy Meadow",
            "Sidewalk",
            "Mosaic Tile",
            "Parquet Floor",
            "Basement Floor",
            "Chessboard Rug",
            "Kiddie Carpet",
            "Shanty Mat",
            "Concrete Floor",
            "Saharah's Desert",
            "Tartan Rug",
            "Palace Tile",
            "Tropical Floor",
            "Playroom Rug",
            "Kitschy Tile",
            "Diner Tile",
            "Block Flooring",
            "Boxing Ring Mat",
            "Harvest Rug",
            "Nook's Cranny Floor",
            "Nook 'n' Go Floor",
            "Nookway Floor",
            "Nookington's Floor"
        };

        public static string[] Wallpaper = new string[71]
        {
            "Chic Wall",
            "Classic Wall",
            "Parlor Wall",
            "Stone Wall",
            "Blue-Trim Wall",
            "Plaster Wall",
            "Classroom Wall",
            "Lovely Wall",
            "Exotic Wall",
            "Mortar Wall",
            "Gold Screen Wall",
            "Tea Room Wall",
            "Citrus Wall",
            "Cabin Wall",
            "Blue Tarp",
            "Lunar Horizon",
            "Garden Wall",
            "Spooky Wall",
            "Western Vista",
            "Green Wall",
            "Blue Wall",
            "Regal Wall",
            "Ranch Wall",
            "Modern Wall",
            "Cabana Wall",
            "Snowman Wall",
            "Backyard Fence",
            "Music Room Wall",
            "Plaza Wall",
            "Lattice Wall",
            "Ornate Wall",
            "Modern Screen",
            "Bamboo Wall",
            "Kitchen Wall",
            "Old Brick Wall",
            "Stately Wall",
            "Imperial Wall",
            "Manor Wall",
            "Ivy Wall",
            "Mod Wall",
            "Rose Wall",
            "Wood Paneling",
            "Concrete Wall",
            "Office Wall",
            "Ancient Wall",
            "Exquisite Wall",
            "Sandlot Wall",
            "Jingle Wall",
            "Meadow Vista",
            "Tree-Lined Wall",
            "Mosaic Wall",
            "Arched Window",
            "Basement Wall",
            "Backgammon Wall",
            "Kiddie Wall",
            "Shanty Wall",
            "Industrial Wall",
            "Desert Vista",
            "Library Wall",
            "Floral Wall",
            "Tropical Vista",
            "Playroom Wall",
            "Kitschy Wall",
            "Groovy Wall",
            "Mushroom Mural",
            "Ringside Seating",
            "Harvest Wall",
            "Nook's Cranny Wall",
            "Nook 'n' Go Wall",
            "Nookway Wall",
            "Nookington's Wall"
        };

        public static string[] e_plus_Carpets = new string[73]
        {
            "Plush Carpet",
            "Classic Carpet",
            "Checkered Tile",
            "Old Flooring",
            "Red Tile",
            "Birch Flooring",
            "Classroom Floor",
            "Lovely Carpet",
            "Exotic Rug",
            "Mossy Carpet",
            "18 Mat Tatami",
            "8 Mat Tatami",
            "Citrus Carpet",
            "Cabin Rug",
            "Closed Road",
            "Lunar Surface",
            "Sand Garden",
            "Spooky Carpet",
            "Western Desert",
            "Green Rug",
            "Blue Flooring",
            "Regal Carpet",
            "Ranch Flooring",
            "Modern Tile",
            "Cabana Flooring",
            "Snowman Carpet",
            "Backyard Lawn",
            "Music Room Floor",
            "Plaza Tile",
            "Kitchen Tile",
            "Ornate Rug",
            "Tatami Floor",
            "Bamboo Flooring",
            "Kitchen Flooring",
            "Charcoal Tile",
            "Stone Tile",
            "Imperial Tile",
            "Opulent Rug",
            "Slate Flooring",
            "Ceramic Tile",
            "Fancy Carpet",
            "Cowhide Rug",
            "Steel Flooring",
            "Office Flooring",
            "Ancient Tile",
            "Exquisite Rug",
            "Sandlot",
            "Jingle Carpet",
            "Daisy Meadow",
            "Sidewalk",
            "Mosaic Tile",
            "Parquet Floor",
            "Basement Floor",
            "Chessboard Rug",
            "Kiddie Carpet",
            "Shanty Mat",
            "Concrete Floor",
            "Saharah's Desert",
            "Tartan Rug",
            "Palace Tile",
            "Tropical Floor",
            "Playroom Rug",
            "Kitschy Tile",
            "Diner Tile",
            "Block Flooring",
            "Boxing Ring Mat",
            "Harvest Rug",
            "Bathhouse Floor",
            "Japanese Floor",
            "Nook's Cranny Floor",
            "Nook 'n' Go Floor",
            "Nookway Floor",
            "Nookington's Floor"
        };

        public static string[] e_plus_Wallpaper = new string[73]
        {
            "Chic Wall",
            "Classic Wall",
            "Parlor Wall",
            "Stone Wall",
            "Blue-Trim Wall",
            "Plaster Wall",
            "Classroom Wall",
            "Lovely Wall",
            "Exotic Wall",
            "Mortar Wall",
            "Gold Screen Wall",
            "Tea Room Wall",
            "Citrus Wall",
            "Cabin Wall",
            "Blue Tarp",
            "Lunar Horizon",
            "Garden Wall",
            "Spooky Wall",
            "Western Vista",
            "Green Wall",
            "Blue Wall",
            "Regal Wall",
            "Ranch Wall",
            "Modern Wall",
            "Cabana Wall",
            "Snowman Wall",
            "Backyard Fence",
            "Music Room Wall",
            "Plaza Wall",
            "Lattice Wall",
            "Ornate Wall",
            "Modern Screen",
            "Bamboo Wall",
            "Kitchen Wall",
            "Old Brick Wall",
            "Stately Wall",
            "Imperial Wall",
            "Manor Wall",
            "Ivy Wall",
            "Mod Wall",
            "Rose Wall",
            "Wood Paneling",
            "Concrete Wall",
            "Office Wall",
            "Ancient Wall",
            "Exquisite Wall",
            "Sandlot Wall",
            "Jingle Wall",
            "Meadow Vista",
            "Tree-Lined Wall",
            "Mosaic Wall",
            "Arched Window",
            "Basement Wall",
            "Backgammon Wall",
            "Kiddie Wall",
            "Shanty Wall",
            "Industrial Wall",
            "Desert Vista",
            "Library Wall",
            "Floral Wall",
            "Tropical Vista",
            "Playroom Wall",
            "Kitschy Wall",
            "Groovy Wall",
            "Mushroom Mural",
            "Ringside Seating",
            "Harvest Wall",
            "Bathhouse Wall",
            "Japanese Wall",
            "Nook's Cranny Wall",
            "Nook 'n' Go Wall",
            "Nookway Wall",
            "Nookington's Wall"
        };
    }
}
